### ISSUE TITLE
为什么这个选座控件是不规整的，两遍还有空白区域，这个要怎么设置

### ISSUE THREAD

**Issue by zhaoxiuyu** [AriadneThread/android-seatview#2]
为什么这个选座控件是不规整的，两遍还有空白区域，这个要怎么设置

**Comment by wuzhendev** [comment]
空白区域指的是哪里？不规整是因为影厅座位的数据就是不规整的

**Comment by zhaoxiuyu** [comment]
数据就是不规整的？好难看懂啊，哪里的数据
![g8ng5g z7i sj6 20cg mk](https://user-images.githubusercontent.com/16554580/50767754-f9753000-12b8-11e9-98d9-c1c714eb4f26.png)

**Comment by zhaoxiuyu** [comment]
类似于电影选座的需求

**Comment by zhaoxiuyu** [comment]
能提供一个规整的数据吗

**Comment by wuzhendev** [comment]
这些数据是你们自己的业务数据，你那边需要把自己的业务数据的字段和控件中的Seat的属性对应起来，这个控件是之前我们公司提供给合作方使用的，数据源是我们提供的，没有考虑太多的通用性，不能满足需求可以修改源码
